name: build # workflow name

on: # initiate the workflow on pushes to master
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  # try build the library
  build:
    runs-on: ubuntu-latest  # using ubuntu

    steps:
    - uses: actions/checkout@v2 # github action
    - name: set up JDK 1.8  # step 1. check Java
      uses: actions/setup-java@v1  
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew 
      run: chmod +x gradlew  # check if gradlew can be run
    - name: Build with Gradle
      run: ./gradlew build  # run gradle build
